var ServicesIndex1 = 0;

var ServicesIndex2 = 0;

var ListServices1 = [
    { image : "url(images/service1_1.jpg)",
      textRUS : "Услуга1 1",
	  textUK : "Service1 1",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
	{ image : "url(images/service1_2.jpg)",
      textRUS : "Услуга1 2",
	  textUK : "Service1 2",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
    { image : "url(images/service1_3.jpg)",
      textRUS : "Услуга1 3",
	  textUK : "Service1 3",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
    { image : "url(images/service1_4.jpg)",
      textRUS : "Услуга1 4",
	  textUK : "Service1 4",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
    { image : "url(images/service1_5.jpg)",
      textRUS : "Услуга1 5",
	  textUK : "Service1 5",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
	{ image : "url(images/service1_6.jpg)",
      textRUS : "Услуга1 6",
	  textUK : "Service1 6",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
    { image : "url(images/service1_7.jpg)",
      textRUS : "Услуга1 7",
	  textUK : "Service1 7",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
    { image : "url(images/service1_8.jpg)",
      textRUS : "Услуга1 8",
	  textUK : "Service1 8",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
    { image : "url(images/service1_9.jpg)",
      textRUS : "Услуга1 9",
	  textUK : "Service1 9",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""}, 	  
    { image : "url(images/service1_10.jpg)",
      textRUS : "Услуга1 10",
	  textUK: "Service1 10",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""}	  
];

var ListServices2 = [
    { image : "url(images/service2_1.jpg)",
      textRUS : "Услуга2 1",
	  textUK : "Service2 1",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
	{ image : "url(images/service2_2.jpg)",
      textRUS : "Услуга2 2",
	  textUK : "Service2 2",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
    { image : "url(images/service2_3.jpg)",
      textRUS : "Услуга2 3",
	  textUK : "Service2 3",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
    { image : "url(images/service2_4.jpg)",
      textRUS : "Услуга2 4",
	  textUK : "Service2 4",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
    { image : "url(images/service2_5.jpg)",
      textRUS : "Услуга2 5",
	  textUK : "Service2 5",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
	{ image : "url(images/service2_6.jpg)",
      textRUS : "Услуга2 6",
	  textUK : "Service2 6",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""},
    { image : "url(images/service2_7.jpg)",
      textRUS : "Услуга2 7",
	  textUK : "Service2 7",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : ""}
];