
var ProductIndex = 0;

var ListProducts = [
    { image : "url(images/product1.jpg)", 
      textRUS : "ARM-Director </br> Система автоматизации мероприятий",
	  textUK : "ARM-Director </br> System of automation </br> of performances",
	  textcolor : "white",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : "pages/products/product1.html"},
	{ image : "url(images/product2.jpg)",
      textRUS : "Продукт 2",
	  textUK : "Product 2",
	  textcolor : "white",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : "pages/products/product2.html"},
    { image : "url(images/product3.jpg)",
      textRUS : "Продукт 3",
	  textUK : "Product 3",
	  textcolor : "black",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : "pages/products/product3.html"},
    { image : "url(images/product4.jpg)",
      textRUS : "Продукт 4",
	  textUK : "Product 4",
	  textcolor : "white",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : "pages/products/product4.html"},
    { image : "url(images/product5.jpg)",
      textRUS : "Продукт 5",
	  textUK : "Product 5",
	  textcolor : "white",
	  description : "",
      page : "pages/products/product5.html"},
    { image : "url(images/product6.jpg)",
      textRUS : "Продукт 6",
	  textUK : "Product 6",
	  textcolor : "white",
	  descriptionRUS : "",
	  descriptionUK : "",
      page : "pages/products/product6.html"}	  
];